# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NaturalDashboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'BaseFramework', :path => '../BaseFramework'
    pod 'NaturalHome', :path => '../NaturalHome'

  # Pods for NaturalDashboard

  target 'NaturalDashboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
target 'NaturalDashboardApps' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'NaturalDashboard', :path => '../NaturalDashboard'
    
    # Pods for NaturalDashboard
    
    target 'NaturalDashboardAppsTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
