# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NaturalHome' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'BaseFramework', :path => '../BaseFramework'

  # Pods for NaturalHome

  target 'NaturalHomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
