# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'BaseFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'HexColors', :git => 'https://github.com/mRs-/HexColors.git', :tag => '6.0.0'
  
  # Pods for BaseFramework

  target 'BaseFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
